# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80533a6274225f3b22cdf5ba6efd346fa81c479191c526af1d9b43f05075d51be55fb7f129a185cd222ce533f03d51799c5e856edbf42204927235415178d686

test:
  secret_key_base: 489df658e881288c4d29867fb0e052a1ffc6bc4de2f2908e3788e6030a915f3652a758cbd23348605740703816a2b62a6f2447a0c97ea6e93dc139fbe63a9ab7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
